#!/bin/bash
#
# Build, package, (optionally) sign + notarize, and (optionally) Sparkle-sign
# a release DMG of ClaudeAutoResume.
#
# Usage:
#   ./Scripts/release.sh <version>
#
# Example:
#   ./Scripts/release.sh 1.0.0
#
# What this does, always:
#   1. Builds the ClaudeAutoResumeApp scheme in Release configuration.
#   2. Packages the resulting .app into a .dmg under dist/.
#
# What this does conditionally (each step is skipped with a clear message if
# its prerequisites aren't set up yet — see README "Code signing &
# notarization" and "Auto-updates" sections):
#   3. Codesigns the .app with a Developer ID Application identity, if
#      DEVELOPER_ID_APPLICATION is set.
#   4. Notarizes + staples the .dmg, if DEVELOPER_ID_APPLICATION and
#      NOTARYTOOL_PROFILE are both set.
#   5. Prints a Sparkle EdDSA signature for the .dmg (to paste into
#      appcast.xml), if `sign_update` is on PATH and SPARKLE_PRIVATE_KEY_PATH
#      is set.
#
# Environment variables:
#   DEVELOPER_ID_APPLICATION  "Developer ID Application: Your Name (TEAMID)"
#                             — find via: security find-identity -v -p codesigning
#   NOTARYTOOL_PROFILE        Keychain profile name created via:
#                               xcrun notarytool store-credentials
#   SPARKLE_PRIVATE_KEY_PATH  Path to the EdDSA private key generated by
#                             Sparkle's `generate_keys` tool. NEVER commit
#                             this file (see .gitignore).

set -euo pipefail

VERSION="${1:?Usage: $0 <version>  (e.g. 1.0.0)}"

PROJECT="ClaudeAutoResume.xcodeproj"
SCHEME="ClaudeAutoResumeApp"
PRODUCT="ClaudeAutoResumeApp.app"
APP_NAME="ClaudeAutoResume"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

BUILD_DIR="build/release-${VERSION}"
DIST_DIR="dist"
APP_PATH="${BUILD_DIR}/Build/Products/Release/${PRODUCT}"
DMG_PATH="${DIST_DIR}/${APP_NAME}-${VERSION}.dmg"

echo "==> Building ${SCHEME} (Release) for version ${VERSION}…"
xcodebuild \
    -project "$PROJECT" \
    -scheme "$SCHEME" \
    -configuration Release \
    -derivedDataPath "$BUILD_DIR" \
    build

if [ ! -d "$APP_PATH" ]; then
    echo "error: built app not found at $APP_PATH" >&2
    exit 1
fi

mkdir -p "$DIST_DIR"

if [ -n "${DEVELOPER_ID_APPLICATION:-}" ]; then
    echo "==> Codesigning with Developer ID: ${DEVELOPER_ID_APPLICATION}…"
    codesign --force --deep --options runtime \
        --sign "$DEVELOPER_ID_APPLICATION" \
        "$APP_PATH"
    codesign --verify --deep --strict --verbose=2 "$APP_PATH"
else
    echo "==> Skipping codesign — DEVELOPER_ID_APPLICATION not set."
    echo "    The DMG will trigger a Gatekeeper warning until this is set up"
    echo "    (see README 'Code signing & notarization')."
fi

echo "==> Creating DMG at ${DMG_PATH}…"
rm -f "$DMG_PATH"
hdiutil create -volname "$APP_NAME" -srcfolder "$APP_PATH" -ov -format UDZO "$DMG_PATH"

if [ -n "${DEVELOPER_ID_APPLICATION:-}" ] && [ -n "${NOTARYTOOL_PROFILE:-}" ]; then
    echo "==> Submitting for notarization (profile: ${NOTARYTOOL_PROFILE})…"
    xcrun notarytool submit "$DMG_PATH" --keychain-profile "$NOTARYTOOL_PROFILE" --wait
    echo "==> Stapling notarization ticket…"
    xcrun stapler staple "$DMG_PATH"
else
    echo "==> Skipping notarization — DEVELOPER_ID_APPLICATION and/or NOTARYTOOL_PROFILE not set."
fi

if command -v sign_update >/dev/null 2>&1 && [ -n "${SPARKLE_PRIVATE_KEY_PATH:-}" ]; then
    echo "==> Generating Sparkle EdDSA signature for appcast.xml…"
    sign_update "$DMG_PATH" -f "$SPARKLE_PRIVATE_KEY_PATH"
    echo "    ^ paste the sparkle:edSignature value above into appcast.xml"
else
    echo "==> Skipping Sparkle signature — sign_update and/or SPARKLE_PRIVATE_KEY_PATH not set."
    echo "    Install sign_update via: brew install sparkle"
fi

DMG_SIZE=$(stat -f%z "$DMG_PATH")

echo
echo "==> Done. Output: ${DMG_PATH} (${DMG_SIZE} bytes)"
echo
echo "Next steps:"
echo "  1. Update appcast.xml with this version's entry (version, "
echo "     shortVersionString, pubDate, enclosure url/length/edSignature)."
echo "  2. git add appcast.xml && git commit -m 'Release v${VERSION}'"
echo "  3. git tag v${VERSION} && git push origin main v${VERSION}"
echo "  4. gh release create v${VERSION} '${DMG_PATH}' --title 'v${VERSION}' --notes '...'"
